version: '3'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db
    command: [ "uvicorn",  "main:app", "--host", "0.0.0.0", "--port", "8080"]


  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "listen_addresses=0.0.0.0",
        "-c",
        "max_connections=200",
      ]


volumes:
  postgres-db:
